__title__ = 'drf-errors-formatter'
__description__ = 'Format errors in Django Rest Framework.'
__url__ = 'https://github.com/thomas545/drf-errors-formatter'
__version__ = '1.0.0'
__author__ = '@thomas545 https://github.com/thomas545'
__author_email__ = 'thomas.adel31@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2021 @thomas545 https://github.com/thomas545'
